# Generated by Django 2.2.12 on 2022-07-10 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movie_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='magnet_link',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='movie',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
