# Generated by Django 2.2.12 on 2022-07-10 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20220710_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='magnet_link',
            field=models.CharField(max_length=10000),
        ),
    ]
